config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users 
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  resources :friends
  # get 'home/index'
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:First_name, :Last_name, :Email, :Phone, :Address, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<br/>
  <div class="form-group">
    <%= form.text_field :First_name, class:"form-control", placeholder:"First name" %>
  </div><br/>

  <div class="form-group">
    <%= form.text_field :Last_name, class:"form-control", placeholder:"Last name"%>
  </div><br/>

  <div class="form-group">
    <%= form.text_field :Email, class:"form-control", placeholder:"Email" %>
  </div><br/>

  <div class="form-group">
    <%= form.text_field :Phone, class:"form-control", placeholder:"Phone" %>
  </div><br/>

  <div class="form-group">
      <%= form.text_field :Address, class:"form-control", placeholder:"Address" %>
  </div><br/>

  <div class="form-group">
      <%= form.text_field :user_id, class:"form-control", id: :friend_user_id, value: current_user.id, type: :hidden %>
  </div><br/>


  <div>
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.First_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.Last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.Email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.Phone %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= friend.Address %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:'btn btn-secondary' %> 
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>

<h1>Friends</h1>
<br/>

<table class="table table-striped table-hover table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Address</th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
    <% if friend.user == current_user %>
    <tr>
      <td> <%= friend.First_name %> </td>
      <td> <%= friend.Last_name %> </td>
      <td> <%= friend.Email %> </td>
      <td> <%= friend.Phone %> </td>
      <td> <%= friend.Address %> </td>
      <td> <%= friend.user_id %> </td>

      <td> <%= link_to 'Show', friend, class: "btn btn-outline-secondary btn-sm" %> </td>
      <td> <%= link_to 'Edit', edit_friend_path(friend), class: "btn btn-outline-info btn-sm" %> </td>
      <td> <%= link_to 'Destroy', friend , method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %> </td>
      </tr>
      <% end %>
      <% end %>
  </tbody>
</table>

<%= link_to "New friend", new_friend_path, class:"btn btn-primary" %>

<% else %>
 <h2><center>... Welcome to Friends App ...</center></h2>
 <h6><center>Please login or Sign-Up to proceed</center></h6>
 <div class="container">

  <div class="row">
    <div class="col-sm">
      <img src="friends.PNG" class="img-fluid float-left" alt="Responsive image" style="size: 150px;">
    </div>
   
    <div class="col-sm">
      <img src="friends2.PNG" class="img-fluid float-right" alt="Responsive image" style="size: 100px;">
  </div>
</div>
</div>




 <%end%>

app/views/friends/new.html.erb
<h1>Add New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <h1 class="display-4">
    <%= @friend.First_name %> <%= @friend.Last_name %>
    </h1>

  <hr class="my-4">
  <p><%= @friend.Email %> | <%= @friend.Phone %></p>
  <p><%= @friend.Address %></p>
  <p class="lead">
    <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-warning" %> 
  <%= link_to "Back", friends_path, class:"btn btn-dark"%>
  <%= button_to "Destroy", @friend, method: :delete, class:"btn btn-danger" %>
  </p>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="padding-left: 15px; padding-right: 15px;">
        	<%= link_to "Friends App", root_path, class:"navbar-brand"  %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      	<%= link_to "Home", root_path, class:"nav-link"  %>
   
      </li>
      <li class="nav-item">
      	<%= link_to "About Us", home_about_path, class:"nav-link"  %>
      </li>
      <li class="nav-item">
      	<%= link_to "Friends", friends_path, class:"nav-link"  %>
      </li>

      <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, class:"nav-link"  %>
          </li>

      <% else %>
          <li class="nav-item">
            <%= link_to "Sign In",  new_user_session_path, class:"nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"  %>
          </li>
      <% end %>
      
      </li>



    </ul>
  </div>
</nav><br/><br/>

app/views/home/about.html.erb
<center><h2>About Us!</h2></center>
<br/>
<div class="container">
<div class="row">
	<div class="col-sm-6">
		Hello there! This is the friend web app from where you can enlist your friends of your knowledge, those who are more old to you. The old friend is usually is the best friend like a friend of school life or belongs from primary school.
	</div>
	
	<div class="col-sm-6">
		The friends are more likely with your feelings and emotions. To do not forget each and everyone from any aspect, this web app helps you to rmember yor each friends in a manner so that no other one will never going to see your private friend list.
	</div>
</div>
</div>
<br/>
<h4>Contact: +92 320 0400 246</h4>
<br/>
<h4>Location: Empress road, Lahore</h4>

app/views/home/index.html.erb
<center><h2>Welcome to Friends App</h2></center>
<br/>
<center><img src="dribbble_gif.gif"></center>

app/views/layouts/_alerts.html.erb
<div class="alert alert-info alert-dismissible fade show" role="alert">
  <%= notice %>
 <span type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
  <!-- <span aria-hidden="true">&times;</span></span> -->
  </span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
   <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/header'%>

    <div class="container">
      <% if notice %>
      <%= render 'layouts/alerts' %>
      <% end %>

      <br/>
      <%= yield %>
    </div>
    
  </body>
</html>